server:
  port: 9081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chatbotspringcloud?currentSchema=chatbotspringcloud
    username: postgres
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000
    queue:
      batch-size: 10
  flyway:
    enabled: true
    schemas: knowledge
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

milvus:
  host: localhost
  port: 19530
  search:
    nprobe: 50
    score-threshold: 0.9
  index:
    m: 8
    ef-construction: 64

embedding:
  url: http://localhost:8000/embeddings
  vector-dim: 384

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      schema: knowledge 