apiVersion: v1
kind: Secret
metadata:
  name: chatbot-secret
  namespace: chatbot
  labels:
    app: chatbot
    component: secret
type: Opaque
data:
  # Base64编码的敏感信息
  # echo -n "postgres" | base64
  DB_USERNAME: cG9zdGdyZXM=
  
  # echo -n "123456" | base64
  DB_PASSWORD: MTIzNDU2
  
  # echo -n "your-jwt-secret" | base64
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0
  
  # echo -n "nacos" | base64
  NACOS_USERNAME: bmFjb3M=
  
  # echo -n "nacos" | base64
  NACOS_PASSWORD: bmFjb3M=
  
  # echo -n "redis-password" | base64
  REDIS_PASSWORD: cmVkaXMtcGFzc3dvcmQ=
  
  # echo -n "rocketmq-password" | base64
  ROCKETMQ_PASSWORD: cm9ja2V0bXEtcGFzc3dvcmQ= 