server:
  port: 8080

spring:
  application:
    name: gateway-service
  
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: chatbot
        group: DEFAULT_GROUP
      config:
        server-addr: 127.0.0.1:8848
        namespace: chatbot
        group: DEFAULT_GROUP
        file-extension: yaml
    
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Sentinel
              args:
                resource: user-service
        
        # 认证服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
            - name: Sentinel
              args:
                resource: auth-service
        
        # 聊天服务路由
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
            - name: Sentinel
              args:
                resource: chat-service
        
        # 知识库服务路由
        - id: knowledge-service
          uri: lb://knowledge-service
          predicates:
            - Path=/api/knowledge/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 15
                redis-rate-limiter.burstCapacity: 30
            - name: Sentinel
              args:
                resource: knowledge-service
    
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
      datasource:
        ds:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: gateway-sentinel-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
            namespace: chatbot

  # Redis配置（用于限流）
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
    com.alibaba.csp.sentinel: DEBUG 